# Generated by Django 5.2.5 on 2025-08-23 23:23

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.profile_image_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.blog_image_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_path),
        ),
    ]
